import type { ProjectEntity } from 'entities'

export const PROJECTS: ProjectEntity.Model.Types.Project[] = [
  {
    id: 'project-1',
    title: 'Project 1',
    tags: [
      'React',
      'TypeScript',
      'TailwindCSS',
      'React',
      'TypeScript',
      'TailwindCSS',
      'React',
      'TypeScript',
      'TailwindCSS',
    ],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    category: 'commercial',
    description:
      'A brief description of Project 1.A brief description of Project 1.A brief description of Project 1.A brief description of Project 1.A brief description of Project 1.A brief description of Project 1.',
  },
  {
    id: 'project-2',
    title: 'Project 2',
    tags: ['Vue.js', 'JavaScript', 'CSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    category: 'commercial',
    description: 'A brief description of Project 2.',
  },
  {
    id: 'project-3',
    title: 'Project 1',
    tags: ['React', 'TypeScript', 'TailwindCSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    category: 'commercial',
    description: 'A brief description of Project 1.',
  },
  {
    id: 'project-4',
    title: 'Project 2',
    tags: ['Vue.js', 'JavaScript', 'CSS'],
    category: 'commercial',
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 2.',
  },
  {
    id: 'project-5',
    title: 'Project 1',
    tags: ['React', 'TypeScript', 'TailwindCSS'],
    category: 'commercial',
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 1.',
  },
  {
    id: 'project-6',
    title: 'Project 2',
    category: 'commercial',
    tags: ['Vue.js', 'JavaScript', 'CSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 2.',
  },
  {
    id: 'project-5',
    title: 'Project 1',
    category: 'commercial',
    tags: ['React', 'TypeScript', 'TailwindCSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 1.',
  },
  {
    id: 'project-6',
    title: 'Project 2',
    category: 'commercial',
    tags: ['Vue.js', 'JavaScript', 'CSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 2.',
  },
  {
    id: 'project-5',
    title: 'Project 1',
    category: 'commercial',
    tags: ['React', 'TypeScript', 'TailwindCSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 1.',
  },
  {
    id: 'project-6',
    title: 'Project 2',
    category: 'commercial',
    tags: ['Vue.js', 'JavaScript', 'CSS'],
    imageSrc: '/images/projects/commercial/ava-security-services.png',
    description: 'A brief description of Project 2.',
  },
]
